// TODO: implement real HTTP scraping
import { BaseAdapter } from './base-adapter.js';
import type { ScrapedRecord } from './base-adapter.js';

export class MaricopaAdapter extends BaseAdapter {
  countyFips = '04013';
  countyName = 'Maricopa County';
  state = 'AZ';

  async scrape(): Promise<ScrapedRecord[]> {
    return [
      {
        rawParcelId: '111200340',
        rawAddress: '1234 E McDowell Rd Phoenix AZ 85006',
        ownerName: 'SMITH BARRY D',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 4320.00,
        dateFiled: '2023-04-10',
        yearsDelinquent: 2,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '212340050',
        rawAddress: '5678 W Camelback Rd Glendale AZ 85301',
        ownerName: 'REYES LOUISA M',
        propertyType: 'residential',
        signalType: 'notice_of_trustee_sale',
        amount: 175000.00,
        dateFiled: '2024-02-14',
        caseNumber: 'NOTS-2024-00891',
        lenderName: 'ARIZONA MORTGAGE GROUP',
        auctionDate: '2024-04-16',
        source: 'Maricopa County Recorder',
      },
      {
        rawParcelId: '301560180',
        rawAddress: '9000 S Central Ave Phoenix AZ 85042',
        ownerName: 'JOHNSON CARLA P',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 7800.50,
        dateFiled: '2022-08-25',
        yearsDelinquent: 3,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '133780090',
        rawAddress: '2200 E Thomas Rd Phoenix AZ 85016',
        ownerName: 'WILLIAMS DEREK A',
        propertyType: 'residential',
        signalType: 'lis_pendens',
        amount: 198000.00,
        dateFiled: '2024-01-19',
        caseNumber: 'LP-2024-MC-00304',
        lenderName: 'PINNACLE BANK',
        source: 'Maricopa County Superior Court',
      },
      {
        rawParcelId: '400230140',
        rawAddress: '4400 N 7th Ave Phoenix AZ 85013',
        ownerName: 'GARCIA JOSE L',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 3600.00,
        dateFiled: '2023-07-05',
        yearsDelinquent: 1,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '501890260',
        rawAddress: '1100 S Mill Ave Tempe AZ 85281',
        ownerName: 'JONES PATRICIA N',
        propertyType: 'commercial',
        signalType: 'tax_lien',
        amount: 29400.00,
        dateFiled: '2021-12-01',
        yearsDelinquent: 5,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '214560320',
        rawAddress: '8800 W Indian School Rd Phoenix AZ 85037',
        ownerName: 'BROWN LISA K',
        propertyType: 'residential',
        signalType: 'notice_of_default',
        amount: 232000.00,
        dateFiled: '2024-03-07',
        caseNumber: 'NOD-2024-MC-00556',
        lenderName: 'MOVEMENT MORTGAGE',
        source: 'Maricopa County Recorder',
      },
      {
        rawParcelId: '305410070',
        rawAddress: '6700 E Camelback Rd Scottsdale AZ 85251',
        ownerName: 'DAVIS MICHAEL F',
        propertyType: 'residential',
        signalType: 'lis_pendens',
        amount: 415000.00,
        dateFiled: '2024-02-01',
        caseNumber: 'LP-2024-MC-00512',
        lenderName: 'BANK OF AMERICA NA',
        source: 'Maricopa County Superior Court',
      },
      {
        rawParcelId: '112690200',
        rawAddress: '3300 W Bethany Home Rd Phoenix AZ 85017',
        ownerName: 'MILLER THOMAS R',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 5550.00,
        dateFiled: '2023-02-22',
        yearsDelinquent: 2,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '430780130',
        rawAddress: '4000 E Southern Ave Mesa AZ 85206',
        ownerName: 'MARTINEZ ANGELA',
        propertyType: 'residential',
        signalType: 'notice_of_trustee_sale',
        amount: 145000.00,
        dateFiled: '2024-01-30',
        caseNumber: 'NOTS-2024-MC-00422',
        lenderName: 'LOANDEPOT',
        auctionDate: '2024-03-26',
        source: 'Maricopa County Recorder',
      },
      {
        rawParcelId: '220150090',
        rawAddress: '2500 W Peoria Ave Phoenix AZ 85029',
        ownerName: 'WILSON BARBARA E',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 2900.00,
        dateFiled: '2024-01-12',
        yearsDelinquent: 1,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '510390170',
        rawAddress: '7200 S Rural Rd Tempe AZ 85283',
        ownerName: 'TAYLOR ROBERT G',
        propertyType: 'residential',
        signalType: 'lis_pendens',
        amount: 320000.00,
        dateFiled: '2023-12-18',
        caseNumber: 'LP-2023-MC-09876',
        lenderName: 'WELLS FARGO BANK NA',
        source: 'Maricopa County Superior Court',
      },
      {
        rawParcelId: '314520280',
        rawAddress: '1800 E Baseline Rd Chandler AZ 85225',
        ownerName: 'ANDERSON HENRY J',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 10200.00,
        dateFiled: '2022-03-14',
        yearsDelinquent: 4,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '421080060',
        rawAddress: '3600 W Thunderbird Rd Phoenix AZ 85053',
        ownerName: 'THOMAS CYNTHIA A',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 6720.00,
        dateFiled: '2023-06-09',
        yearsDelinquent: 2,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '103450110',
        rawAddress: '5000 E Van Buren St Phoenix AZ 85008',
        ownerName: 'JACKSON PAUL R',
        propertyType: 'commercial',
        signalType: 'tax_lien',
        amount: 37500.00,
        dateFiled: '2021-09-28',
        yearsDelinquent: 5,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '312870190',
        rawAddress: '2100 W Guadalupe Rd Gilbert AZ 85233',
        ownerName: 'WHITE NANCY L',
        propertyType: 'residential',
        signalType: 'notice_of_default',
        amount: 267000.00,
        dateFiled: '2024-02-25',
        caseNumber: 'NOD-2024-MC-00645',
        lenderName: 'NEWREZ LLC',
        source: 'Maricopa County Recorder',
      },
      {
        rawParcelId: '430220050',
        rawAddress: '900 S Dobson Rd Mesa AZ 85202',
        ownerName: 'HARRIS JEROME T',
        propertyType: 'residential',
        signalType: 'lis_pendens',
        amount: 185000.00,
        dateFiled: '2023-10-29',
        caseNumber: 'LP-2023-MC-08441',
        lenderName: 'PENNYMAC LOAN SERVICES',
        source: 'Maricopa County Superior Court',
      },
      {
        rawParcelId: '201340370',
        rawAddress: '11000 N 51st Ave Glendale AZ 85304',
        ownerName: 'CLARK FELICIA R',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 4080.00,
        dateFiled: '2023-09-03',
        yearsDelinquent: 2,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '115670240',
        rawAddress: '300 E Osborn Rd Phoenix AZ 85012',
        ownerName: 'LEWIS FRANK D',
        propertyType: 'residential',
        signalType: 'tax_lien',
        amount: 8950.00,
        dateFiled: '2022-11-17',
        yearsDelinquent: 3,
        source: 'Maricopa County Treasurer',
      },
      {
        rawParcelId: '512480090',
        rawAddress: '1300 E Apache Blvd Tempe AZ 85281',
        ownerName: 'ROBINSON KENDRA N',
        propertyType: 'residential',
        signalType: 'notice_of_trustee_sale',
        amount: 120000.00,
        dateFiled: '2024-03-12',
        caseNumber: 'NOTS-2024-MC-00734',
        lenderName: 'CARRINGTON MORTGAGE',
        auctionDate: '2024-05-21',
        source: 'Maricopa County Recorder',
      },
    ];
  }
}
